### ISSUE TITLE
Change slider arrow color

### ISSUE THREAD

**Issue by Keith-Web3** [shelcia/dynamic-portfolio#176]
The arrow for the slider is barely noticeable especially on white backgrounds. I'll suggest the color be changed.
![Screenshot (33)](https://user-images.githubusercontent.com/96974022/194708441-8daa68e9-92b1-4bcf-9d5d-fb373ffad63b.png)
AS you can see in the screenshot above, the button is not visible.

**Comment by shelcia** [comment]
Please feel free to raise MR

**Comment by pranavajith** [comment]
Hey @shelcia ,
can you assign this to me? I'll start working on it and if finished, will send a PR by 5th.. cool?

**Comment by sidling1** [comment]
can you assign this to me?

**Comment by shelcia** [comment]
@sidling1  it's already assigned

**Comment by srilakshmiv123** [comment]
> The arrow for the slider is barely noticeable especially on white backgrounds. I'll suggest the color be changed. ![Screenshot (33)](https://user-images.githubusercontent.com/96974022/194708441-8daa68e9-92b1-4bcf-9d5d-fb373ffad63b.png) AS you can see in the screenshot above, the button is not visible.

I'm interested to contribute this issue
