### ISSUE TITLE
write Documentation

### ISSUE THREAD

**Issue by shelcia** [shelcia/dynamic-portfolio#192]

**Comment by pranavajith** [comment]
Hey @shelcia 
Could you give some data/source as to how to write documentation?
Thanks!

**Comment by shelcia** [comment]
Try out the app and explain it in readme itself

**Comment by pranavajith** [comment]
Got it!
I would like to start working on this as well.. once I submit my current PR for issue #176 , can I make a PR for this issue as well?

**Comment by SattyamSamania** [comment]
Hey @shelcia if the issue is still open can i work on this?
