### ISSUE TITLE
Need to edit closing dropdown at Navbar for smaller dimensions (sm / md) .

### ISSUE THREAD

**Issue by pranavajith** [shelcia/dynamic-portfolio#198]
To close the dropdown menu is incredibly difficult in any dimension other than lg. This has to be rectified.
<img width="594" alt="Screenshot 2022-12-05 at 12 26 44 AM" src="https://user-images.githubusercontent.com/96235918/205509856-100c46ef-24cd-4155-9f57-ff6219f0703f.png">

**Comment by shivamgupta2020** [comment]
I am interested. Assign this task to me.

**Comment by srilakshmiv123** [comment]
> To close the dropdown menu is incredibly difficult in any dimension other than lg. This has to be rectified. <img alt="Screenshot 2022-12-05 at 12 26 44 AM" width="594" src="https://user-images.githubusercontent.com/96235918/205509856-100c46ef-24cd-4155-9f57-ff6219f0703f.png">

I'm interested to contribute this issue. Can you assign me?

**Comment by pranavajith** [comment]
@shelcia how may I proceed in attempting on solving this?
