### ISSUE TITLE
Edit portfolio option to be enabled - Needs BE

### ISSUE THREAD

**Issue by shelcia** [shelcia/dynamic-portfolio#204]

**Comment by AkashSharma001** [comment]
I would like to work on this.
@shelcia

**Comment by thisguyisbarry** [comment]
Currently looking into this. My thought process is to reuse the template pages in src\pages\dashboard\addPortfolio\templates. 
I want to replace the submit button with an edit button, is it best to do that with a conditional render based on the url?
(e.g. the route add-portfolio/:template will render the edit button for that form, while add-portfolio/:template will render the submit button)

If so, is the best place to put that condition in each of the template form files? (src\pages\dashboard\addPortfolio\templates\Template1.jsx)

**Comment by shelcia** [comment]
You mean the route editPortfolio/:template .. the code would be so much neat if you could reuse the add portfolio component itself

**Comment by thisguyisbarry** [comment]
@AkashSharma001 Have you completed much work on it? I was checking your fork and didn't really see any movement on anything. 

I'd be happy to split up the workload between us if that works for you, this issue seems a bit more interesting to me.

**Comment by AkashSharma001** [comment]
@thisguyisbarry yes I'm working on this. currently, I didn't push to my forked repo. I'm working locally.

**Comment by shelcia** [comment]
@AkashSharma001  hey is it on progress ?

**Comment by AkashSharma001** [comment]
@shelcia Yes
