### ISSUE TITLE
Change carousel arrow color on homepage

### ISSUE THREAD

**Issue by shelcia** [shelcia/dynamic-portfolio#205]
![Screenshot 2022-12-06 at 3 03 53 AM](https://user-images.githubusercontent.com/31156685/205747279-90553dc9-5e40-4da7-9df9-1f96eaa2fe40.png)

**Comment by AlinaRizvi28** [comment]
Please assign it to me

**Comment by Max-Stark07** [comment]
![Screenshot (55)](https://user-images.githubusercontent.com/108427123/205852417-167f9784-9cf7-47f5-9db0-fa567273ff6f.png)
Will you assign me this job?  I am sending a screenshot of my edit. Will this work??

**Comment by shelcia** [comment]
@Max-Stark07  Add something like dark blue which goes with the theme

**Comment by Max-Stark07** [comment]
![Screenshot (56)](https://user-images.githubusercontent.com/108427123/205856607-e767c81c-2ac6-4bb5-8563-a204c010ec53.png)
Now??

**Comment by ankushj0801** [comment]
Can I work on this if it is open? @shelcia
