### ISSUE TITLE
Need 404 page 

### ISSUE THREAD

**Issue by shelcia** [shelcia/dynamic-portfolio#206]

**Comment by SattyamSamania** [comment]
Hey @shelcia I would like to do this issue. Please tell further how should I proceed to create page.

**Comment by shelcia** [comment]
Create a new react file and add code. Make sure the design of it is similar to the design we have . Design ref: https://www.creative-tim.com/product/argon-design-system

**Comment by shelcia** [comment]
run npm i and npm start

**Comment by SattyamSamania** [comment]
> run npm i and npm start

In which file should I add code?

**Comment by shelcia** [comment]
root folder
