### ISSUE TITLE
Add hamburger menu in template 3 on mobile devices

### ISSUE THREAD

**Issue by shelcia** [shelcia/dynamic-portfolio#210]

**Comment by Yogeshlodhi** [comment]
@shelcia Please assign this to me by adding the Codpeak Label

**Comment by Yogeshlodhi** [comment]
What options do you want to have in the hamburger menu?

**Comment by Yogeshlodhi** [comment]
Sorry for inconvenience, Can I work on this issue in html,css and js and
then submit to you?

**Comment by shelcia** [comment]
need react

**Comment by Tushar98644** [comment]
assign me @shelcia

**Comment by AyushK-101** [comment]
@shelcia can I work on this if it's still open?

**Comment by rachit-goyal1071** [comment]
He @shelcia i would like to work on this issue can you assign it to me.

**Comment by rishabhguptajs** [comment]
hey @shelcia , can I work on this issue if it's still open?

**Comment by Bhupendra3444** [comment]
hey @shelcia, I want to work on this. Please assign me under iwoc.
