### ISSUE TITLE
Template 2 - Make the lines white in dark mode

### ISSUE THREAD

**Issue by shelcia** [shelcia/dynamic-portfolio#211]
![Screenshot 2022-12-06 at 1 17 20 PM](https://user-images.githubusercontent.com/31156685/205851956-782f303c-6eee-4996-8ad7-e80b7b09d9a6.png)

**Comment by Kumar-Ankit56** [comment]
@shelcia please assign me.

**Comment by ankushj0801** [comment]
I want to work on this. please assign it to me @shelcia
