### ISSUE TITLE
Template 2 - Add Tooltips for the icons

### ISSUE THREAD

**Issue by shelcia** [shelcia/dynamic-portfolio#212]
![Screenshot 2022-12-06 at 1 19 40 PM](https://user-images.githubusercontent.com/31156685/205852396-1c02fdc1-670e-4e24-8440-4d0b9a824c6c.png)

**Comment by itz-deepak** [comment]
assign this to me

**Comment by ankushj0801** [comment]
Can I work on this? @shelcia
