### ISSUE TITLE
Template 2 - Open in new tab when clicked on the icons

### ISSUE THREAD

**Issue by shelcia** [shelcia/dynamic-portfolio#213]
![Screenshot 2022-12-06 at 1 19 40 PM](https://user-images.githubusercontent.com/31156685/205852589-8090206e-f2e6-4ef3-be16-893658e21f8b.png)

**Comment by Max-Stark07** [comment]
Can you assign me this?

**Comment by Kumar-Ankit56** [comment]
@shelcia please assign me.

**Comment by ankushj0801** [comment]
Can I work on this issue if it is open? @shelcia
