### ISSUE TITLE
Template 1 - Add tooltips for the icons

### ISSUE THREAD

**Issue by shelcia** [shelcia/dynamic-portfolio#215]
![Screenshot 2022-12-06 at 1 25 14 PM 2](https://user-images.githubusercontent.com/31156685/205853515-9e9c18e4-2e74-4e9f-a7b3-758094c3249b.png)

**Comment by Kumar-Ankit56** [comment]
@shelcia please assign me. Let me know what tooltips is mean?

**Comment by ankushj0801** [comment]
Can I work on this issue if it is open? @shelcia
