### ISSUE TITLE
Template 2 - Open in new tab when clicked on the icons

### ISSUE THREAD

**Issue by shelcia** [shelcia/dynamic-portfolio#216]
![Screenshot 2022-12-06 at 1 25 14 PM 2](https://user-images.githubusercontent.com/31156685/205853806-34870a2a-0454-44c9-9717-ae08c810c37d.png)

**Comment by Kumar-Ankit56** [comment]
@shelcia please assign me I would love to work on this.

**Comment by Yogeshlodhi** [comment]
@shelcia  Please assign this issue to me I could make a few more decent changes also

**Comment by ankushj0801** [comment]
Can I work on this if it is open? @shelcia
