### ISSUE TITLE
add a button to collapse menu bar when screen is small

### ISSUE THREAD

**Issue by mpatwa98** [shelcia/dynamic-portfolio#224]
![Screenshot_20221208_205055](https://user-images.githubusercontent.com/96737076/206484733-d636e709-bf2f-4f56-9d1f-2f0ba9396a9a.png)
when screen is small then login and sign up are in hamberger menu then after clicking on that menu it expands but no button to collapse.

**Comment by shelcia** [comment]
duplicate issue https://github.com/shelcia/dynamic-portfolio/issues/198
