### ISSUE TITLE
Want to add search bar and some buttons in template-2. 

### ISSUE THREAD

**Issue by srj06** [shelcia/dynamic-portfolio#226]
There is no search bar in Template-2 (photographer portfolio)  and also some expected buttons like 1. Photos, 2. Diary, 3. contact us.
Need of search bar is to  help people to find out the exact photo from the collection of photos by just entering the collection name. So, I would like to contribute these changes to this template, please assign me this project work.

**Comment by srj06** [comment]
@shelcia  
Please let me know if I can work on this issue?

**Comment by shelcia** [comment]
I don't think we need search bar

**Comment by shelcia** [comment]
What is 'diary' in here

**Comment by srj06** [comment]
Diary is collection of photos  where we have an options like nature, fashion, sports, portrait etc.
