### ISSUE TITLE
Adding Unit Test Cases

### ISSUE THREAD

**Issue by Jagroop2001** [shelcia/dynamic-portfolio#240]
Can I work on this Project?
I can add unit test scripts using jest in this Project.
Please allow me to continue with the same.
About Unit Testing :
Unit Testing is used to check whether the Input fields are working correctly without interaction of any Human.
Here I write a unit tests using Jest which is auto-installed which creating react app.

So I will write a test for each component and the good thing is the code is used for testing only while deploying app it doesn't effect the perfornce but it is useful to test our react app without human intraction.

Hoping to hear from you soon !!

**Comment by Jagroop2000** [comment]
Hi @shelcia !!

I have added test scripts for 2 Components. Please merge this. 
I will add Signup and SignIn Component Test case by Creating New Issue.

**NOTE: Please add points like this. It would be really helpful** 
![Screenshot from 2022-12-15 20-17-54](https://user-images.githubusercontent.com/99062463/208299318-a34ebe6c-c5b2-4ee5-b941-471816baa6a1.png)

**Comment by Jagroop2000** [comment]
Hi @shelcia !!
Please add points on the basis of the Code Evaluation. It would be really helpful.

**Comment by shelcia** [comment]
closing the PR as we have migrated to vite

**Comment by shivam101203** [comment]
@shelcia please assign this issue under iwoc to me
