### ISSUE TITLE
update SECURITY.md

### ISSUE THREAD

**Issue by shelcia** [shelcia/dynamic-portfolio#243]

**Comment by Nityamalviya28** [comment]
hello! @shelcia  can you please explain something more about this issue .

**Comment by Yash-Var** [comment]
@shelcia I want to work can you explain that..

**Comment by shelcia** [comment]
Refer this : https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

**Comment by SAMAD101** [comment]
Where can I find info regarding the supported versions of the project?
