### ISSUE TITLE
Template 1 - Text contrast is poor

### ISSUE THREAD

**Issue by shelcia** [shelcia/dynamic-portfolio#253]
![Screenshot 2022-12-20 at 3 17 31 PM](https://user-images.githubusercontent.com/31156685/208636602-18131008-2060-40ac-adf2-1e20d402b248.png)

Ex: https://dynamic--portfolio.vercel.app/portfolio/630f44611ddb0f899c66e399

**Comment by ankushj0801** [comment]
Please assign me this @shelcia

**Comment by abhinav16aero** [comment]
Please assign this to me.
