### ISSUE TITLE
Template 2 - Loader when loading pictures

### ISSUE THREAD

**Issue by shelcia** [shelcia/dynamic-portfolio#254]
![Screenshot 2022-12-20 at 3 17 57 PM](https://user-images.githubusercontent.com/31156685/208636785-ce552840-3666-4928-9a65-54949bfcc872.png)

ex: https://dynamic--portfolio.vercel.app/portfolio/630f51c81ddb0f899c66e39a

**Comment by MCoder86A** [comment]
Assign this to me.
