### ISSUE TITLE
Animate skill section 

### ISSUE THREAD

**Issue by nik132-eng** [shelcia/dynamic-portfolio#259]
![image](https://user-images.githubusercontent.com/77881638/209422125-3b503cde-73e7-415a-bd54-73abf1944684.png)

add animation and hovering effect in this section

please assign me this issue so I can work on it.

**Comment by AyushK-101** [comment]
@shelcia I would like to work on this if its still open

**Comment by Nivedita-R** [comment]
@shelcia I would like to work on this if its open.

**Comment by livepallav** [comment]
@shelcia I saw the website. I would love to work in this. Please assign me this if it's open.

**Comment by Ayush001612** [comment]
@shelcia I would like to work on this issue under IWOC'23

**Comment by Preeti8021** [comment]
I would like to work on this under CODEPEAK'23!

**Comment by Preeti8021** [comment]
As the deadline for CODEPEAK'23 is over, I request to add kwoc label to this issue. So that this pr gets merged under KWOC'23 program.

**Comment by Preeti8021** [comment]
Kindly add KWOC'23 tag, as the deadline for codepeak is passed.
