### ISSUE TITLE
Add Scroll to Top Button

### ISSUE THREAD

**Issue by SattyamSamania** [shelcia/dynamic-portfolio#271]
I would like to add Scroll to Top button. If you think that would be helpful kindly assign this issue to me. Thank You!

**Comment by SattyamSamania** [comment]
Hey @shelcia In which file should I add the button?

**Comment by shelcia** [comment]
Add in all the templates

**Comment by codemaniac-sahil** [comment]
Hey @shelcia and @SattyamSamania is this issue still open an can i work on this issue.

**Comment by codemaniac-sahil** [comment]
Hey @shelcia, I resolved this issue. Would you please check my PR https://github.com/shelcia/dynamic-portfolio/pull/284

**Comment by itsrishti** [comment]
I want to contribute in this issue please assigned me this project

**Comment by Akanksha038** [comment]
I would like to add Scroll to Top button. If you think that would be helpful, then assigned me this project. Thank You!

**Comment by Ayush001612** [comment]
I would like to contribute in this issue uner IWOC'23

**Comment by Tavish108** [comment]
I would like to contribute in this issue under IWOC'23
