### ISSUE TITLE
Bug in template 1 form validation

### ISSUE THREAD

**Issue by MCoder86A** [shelcia/dynamic-portfolio#272]
After filling all the fields except experience, the submit button doesn't trigger error message.  Below I have attached a video and steps to reproduce it.

[Dynamic-Portfolio_t3.webm](https://user-images.githubusercontent.com/56883128/209900593-9cb0fbac-5b6a-4abc-b8cc-4feaac09f8e9.webm)
#### Steps to reproduce:
* Choose first template
* Fill all the fields except experience
* Without touching any fields of experience, click on submit.

Can I fix this issue?

**Comment by rachit-goyal1071** [comment]
Hlw @shelcia i would like to contribute can you assign me this issue.
