### ISSUE TITLE
Writing a blog on this project in hindi

### ISSUE THREAD

**Issue by Bharadwajshivam28** [shelcia/dynamic-portfolio#290]
Hello Respected sir/mam
   If you like my idea then we can write a Documentation on this project in Hindi Language

Aim of writing Document of Project in  Hindi Language is that Many people understand Hindi language well so one can read the documentation in Hindi language and understand Project well

If you like my idean than we can move ahead

**Comment by Bharadwajshivam28** [comment]
@shelcia If you find it valueable then please assign me this under iwoc with any difficulty tag

**Comment by GitWiz01** [comment]
@shelcia Can you also assign me this issue

**Comment by Bharadwajshivam28** [comment]
thanks for opportunity @shelcia

**Comment by Bharadwajshivam28** [comment]
![Screenshot from 2023-02-19 17-54-00](https://user-images.githubusercontent.com/108119109/219947751-2ccfabf6-4247-4344-8b5b-15e0edf51c41.png)
![Screenshot from 2023-02-19 17-54-16](https://user-images.githubusercontent.com/108119109/219947753-f02f1087-9eab-468b-abb8-baf163ad7e0c.png)

**Comment by Bharadwajshivam28** [comment]
![Screenshot from 2023-02-19 17-54-16](https://user-images.githubusercontent.com/108119109/219947774-cc95ca40-0dec-4092-b0c0-b4c9694e819c.png)

**Comment by Bharadwajshivam28** [comment]
@shelcia PLease close this issue mam as it is merged and completed so i will get my point
