### ISSUE TITLE
[Enhancement] Adding a logo for the site.

### ISSUE THREAD

**Issue by nepalivai** [shelcia/dynamic-portfolio#319]
At the upper right corner instead of just D why not add a logo.
<img width="570" alt="image" src="https://github.com/shelcia/dynamic-portfolio/assets/108126089/ffa4d730-adee-48e1-ba09-b4c169516b5b">

**Comment by nepalivai** [comment]
hey @shelcia, Here is what I came up with tell me if I could make some modifications or if should i implement them.
<img width="380" alt="image" src="https://github.com/shelcia/dynamic-portfolio/assets/108126089/9fdc32b9-f75a-42be-9716-c1efd40710f3">

**Comment by shelcia** [comment]
can we try something different ?

**Comment by Gitjha6** [comment]
I have seen the bug related to logo.
please assign me under iwoc24.

**Comment by nepalivai** [comment]
@shelcia do have any suggestions or something you might like a mood board?
@Gitjha6 feel free to drop your logo idea if it suits our needs I will be happy to give this issue to you.

**Comment by praptisharma28** [comment]
![Screenshot (474)](https://github.com/shelcia/dynamic-portfolio/assets/123169861/f6815154-56e6-4fc1-8f80-0dc78bd295c6)
@shelcia how about something like this?

**Comment by Tavish108** [comment]
![vecteezy_modern-and-elegant-d-letter-initial-logo-design_](https://github.com/shelcia/dynamic-portfolio/assets/123955740/084bb6d7-6ae8-46a5-a4a5-01fca48f6f0f)
What about something like this

**Comment by praptisharma28** [comment]
More ideas @shelcia ![dynamic-portfolio-high-resolution-logo (4)](https://github.com/shelcia/dynamic-portfolio/assets/123169861/2056d4d3-94d7-4d30-8ef1-03cdc9065fd8)
![dynamic-portfolio-high-resolution-logo (4)](https://github.com/shelcia/dynamic-portfolio/assets/123169861/5f6792a6-28b6-45e5-ab4a-b3250cadb61a)
![dynamic-portfolio-high-resolution-logo (3)](https://github.com/shelcia/dynamic-portfolio/assets/123169861/a2157d48-b641-44e1-a882-41bb7353b67e)
![dynamic-portfolio-high-resolution-logo (2)](https://github.com/shelcia/dynamic-portfolio/assets/123169861/d1efdd73-bfc0-46cb-9491-a42ecbf7695b)
![dynamic-portfolio-high-resolution-logo (1)](https://github.com/shelcia/dynamic-portfolio/assets/123169861/f3dff110-4ab2-4748-8b2c-03903343ec66)
![dynamic-portfolio-high-resolution-logo](https://github.com/shelcia/dynamic-portfolio/assets/123169861/97973321-2a1f-4bae-87d8-e06b8965b8c8)

**Comment by shelcia** [comment]
@Tavish108 could you make a PR with favicon and logo in public directory

**Comment by nepalivai** [comment]
hey @shelcia logo seems to be added but it's not included in the website/readme. I am willing to implement it in all places can I start working on it?
