### ISSUE TITLE
[Feature]: Add the GitHub action workflow for Issues and pull requests

### ISSUE THREAD

**Issue by JiyaGupta-cs** [shelcia/dynamic-portfolio#334]
# Description:
The current project lacks an automated action to greet contributors. GitHub Actions can significantly enhance project automation. I propose adding a GitHub Action workflow to assist new pull requests (PR) and issue creators.

# Proposed Changes:
Implement a GitHub Action workflow that triggers new PRs and issues.

**Please assign me this issue under IWOC**

**Comment by shelcia** [comment]
It is implemented already, as you can see one above

**Comment by JiyaGupta-cs** [comment]
@shelcia I have changed the issue title
I want to add issue templates which would assist the contributors to open issues

**Comment by JiyaGupta-cs** [comment]
@shelcia I have made a Pull Request
Could you please change the label from "easy" to "medium"?

**Comment by shelcia** [comment]
@JiyaGupta-cs  sorry ! I don't see the need to change the label

**Comment by JiyaGupta-cs** [comment]
@shelcia please add label of "iwoc2024"

**Comment by JiyaGupta-cs** [comment]
@shelcia please add label of "iwoc2024"
iwoc24 is not counting
