### ISSUE TITLE
Co - Contributor

### ISSUE THREAD

**Issue by Jassi10000-zz** [shelcia/dynamic-portfolio#93]
Hey @shelcia , this project seems interesting to me , can I be a co-contributor in this ?

**Comment by shelcia** [comment]
sure

**Comment by Jassi10000** [comment]
> sure

Can we connect somewhere maybe on a meet or zoom as I have some nice points to discuss about this project

**Comment by shelcia** [comment]
okay sure please schedule a meeting

**Comment by shelcia** [comment]
That's cool !, we can discuss on discord

**Comment by AbhiPatel10** [comment]
@shelcia  Please Provide me your discord username.

**Comment by AbhiPatel10** [comment]
@shelcia  request has been Sended please Check.
